### PR TITLE
misc. tssilomon fixes

### PR DESCRIPTION
**Pull request by joufellasfl**
Here's a set of changes to make the script easier to understand and maintain, apply or pick individually at your convenience.

### CODE REVIEW

**Comment by ts-kris** [comment]
Thank you for these as well!

I havn't had time to set up testing but I should be able to soon.

**Comment by joufellasfl** [comment]
Thank you @ts-kris , note this one would require a bit more testing as we don't have the hardware available. We had to change the /bin/sh shebang to avoid Yocto blocking installation (it checks for interpreters availability), and couldn't make sense of the script, so I sent this PR in parallel. But I think overall it would make sense to simplify it.

**Comment by ts-kris** [comment]
Rebased against main after the shebang change.
Cleaned up some shellcheck warnings and style.
Tested against TS-TPC-7990 Rev C w/ Rev A TS-DC799-SILO on image `2021-12-17`

**Review by ts-kris — APPROVED** [review]

**Review by markfeathers — APPROVED** [review]
Reviewed, not tested.

**Comment by ts-kris** [comment]
I'll re-tag this repo later with a new version, however, I need to figure out what is going on with #5 first

**Pull request merged**
