### PR TITLE
tsmicroctl: Only read as much data as required for the correct platform

### PR DESCRIPTION
**Pull request by markfeathers**
Reading more data than we should causes the i2c transaction to fail on newer kernels.

Split info into board specific functions, removed tmp and copy, swap ADC byte order only.

### CODE REVIEW

**Review by ts-kris — COMMENTED** [review]
Is `do_mac()` used on the 7990 as well? does that need to be fixed up in the same way?

**Comment by ts-kris** [comment]
Fixes #5

**Comment by markfeathers** [comment]
> Is `do_mac()` used on the 7990 as well? does that need to be fixed up in the same way?

It is not, that was used when the 7970 moved to CDC-ACM where the mac address is used as the serial.  This was not moved on the TS-7990 and the micro is unaware of the serial.

**Review by ts-kris — APPROVED** [review]
Reviewed, not tested.

**Pull request merged**
